services:
  postgres:
    image: postgres:15.3-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  mongo:
    image: mongo
    ports:
      - ${CHATBOX_DB_PORT}:27017
    volumes:
      - ./.data/db:/var/lib/mongodb/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CHATBOX_DB_SUPER_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${CHATBOX_DB_SUPER_PASSWORD}
      MONGO_INITDB_DATABASE: ${CHATBOX_DB_NAME}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://${CHATBOX_DB_SUPER_USERNAME}:${CHATBOX_DB_SUPER_PASSWORD}@mongo:27017/

  maildev:
    build:
      context: .
      dockerfile: ./docker-files/maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  chat-redis:
    image: redis:7-alpine
    ports:
      - 6380:6379

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - ./.data/db:/var/lib/redisinsight/data

  friend-reco:
    build:
      context: .
      dockerfile: ./docker-files/friend-reco.Dockerfile
    depends_on:
      - postgres
      - mongo
      - redis
      - friend-job
    command: node dist/apps/friend-recommendation/apps/friend-recommendation/src/main

  friend-job:
    build:
      context: .
      dockerfile: ./docker-files/friend-job.Dockerfile
    depends_on:
      - postgres
      - mongo
      - redis
    command: node dist/apps/friend-job/apps/friend-job/src/main

  post:
    build:
      context: .
      dockerfile: ./docker-files/post.Dockerfile
    depends_on:
      - postgres
      - mongo
      - redis
    command: node dist/apps/post/apps/post/src/main

  post-reco:
    build:
      context: .
      dockerfile: ./docker-files/post-reco.Dockerfile
    depends_on:
      - postgres
      - mongo
      - redis
      - friend-job
      - post
    command: node dist/apps/post-recommendation/apps/post-recommendation/src/main

  main-app:
    build:
      context: .
      dockerfile: ./docker-files/main.Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - friend-job
      - postgres
      - mongo
      - redis
      - friend-reco
      - post
      - post-reco
    command: node dist/apps/main-app/apps/main-app/src/main

  conversation:
    build:
      context: .
      dockerfile: ./docker-files/conversation.Dockerfile
    ports:
      - ${CHAT_PORT}:${CHAT_PORT}
    depends_on:
      - postgres
      - mongo
      - redis
      - chat-redis
    command: node dist/apps/conversation/apps/conversation/src/main
