services:
  postgres:
    image: postgres:15.3-alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CHATBOX_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${CHATBOX_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${CHATBOX_DB_NAME}

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    expose:
      - 1080
      - 1025

  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   expose:
  #     - 6379

  api:
    build:
      context: .
      dockerfile: e2e.Dockerfile
